version: "3"
services:
  mediator:
    image: indicio-tech/aries-mediator
    hostname: mediator
    restart: unless-stopped
    environment:
      - ACAPY_ENDPOINT=[http://{insertDNSEntryHere.com}:3000,ws://{insertDNSEntryHere.com}:3000]
      - ACAPY_WALLET_STORAGE_CONFIG={"url":"db:5432","wallet_scheme":"DatabasePerWallet"}
      - ACAPY_WALLET_STORAGE_CREDS={"account":"insertStringHere","password":"insertStringHere","admin_account":"insertStringHere","admin_password":"insertStringHere"}
      - ACAPY_WALLET_KEY=testing
    volumes:
      - ./wait-for-it:/home/indy/wait-for-it:z
    command: >
      sh -c "./wait-for-it/wait-for-it.sh db:5432 -s -t 60 -- aca-py start --auto-provision --arg-file ./configs/start.yml"
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    networks:
      - mediator-network

  # DB Service
  db:
    image: postgres:10
    hostname: db
    restart: always
    #    ports: # Uncomment to access postgres outside of containers
    #      - "5432:5432"
    environment:
      POSTGRES_USER: insertStringHere
      POSTGRES_PASSWORD: insertStringHere
    networks:
      - mediator-network

#Docker Networks
networks:
  mediator-network:
    driver: bridge
