version: "3"
services:
  ngrok:
    image: wernight/ngrok
    command: ngrok http mediator:3000 --log stdout

  mediator:
    image: oliu-mediator-ngrok
    build:
      context: .
      dockerfile: ./Dockerfile.ngrok
    environment:
      - NGROK_NAME=ngrok
    depends_on:
      - ngrok
    command: aca-py start --arg-file configs/default.yml
