version: '3'
services:

  mediator:
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: mediator
    restart: unless-stopped
    environment:
      - ACAPY_ENDPOINT=[https://${ACAPY_ENDPOINT:-localhost}:443,wss://${ACAPY_ENDPOINT:-localhost}:443]
      - ACAPY_WALLET_STORAGE_CONFIG={"url":"${ACAPY_DB:-db}:5432","wallet_scheme":"DatabasePerWallet"}
      - ACAPY_WALLET_STORAGE_CREDS={"account":"${ACAPY_DB_ACCOUNT:-development}","password":"development","admin_account":"${ACAPY_DB_ADMIN_ACCOUNT:-development}","admin_password":"${ACAPY_DB_ADMIN_PASSWORD:-development}"}
      - ACAPY_WALLET_KEY=${ACAPY_WALLET_KEY:-testing}
    volumes:
      - ./wait-for-it:/home/indy/wait-for-it:z
    command: >
      sh -c "./wait-for-it/wait-for-it.sh ${ACAPY_DB:-db}:5432 -s -t 60 -- aca-py start --auto-provision --arg-file ./configs/start.yml"
    depends_on:
      - "db"
    networks:
      - mediator-network

  # DB Service
  db:
    image: postgres:9.5
    hostname: db
    restart: always
#    ports: # Uncomment to access postgres outside of containers
#      - "5432:5432"
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
    networks:
      - mediator-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    build:
      context: nginx
      dockerfile: Dockerfile-nginx    
    hostname: webserver
    restart: unless-stopped
    environment:
      SSL_DOMAIN_PATH: ${SSL_DOMAIN_PATH} 
    tty: true
    ports:
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:consistent
      - ./nginx/conf.d/:/etc/nginx/templates/
      - ./nginx/docker-entrypoint.d/create-self-signed.sh:/docker-entrypoint.d/10-create-self-signed.sh
      - ./nginx/certbot-path:/certbot-path
    depends_on:
      - "mediator"
    networks:
      - mediator-network



#Docker Networks
networks:
  mediator-network:
    driver: bridge
